server:
  port: ${GATEWAY_PORT}
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: AUTH-SERVICE
          uri: http://localhost:${AUTH-SERVICE-PORT}
          predicates:
            - Path=/api/auth/**
        - id: DEPARTMENT-SERVICE
          uri: http://localhost:${DEPARTMENT-SERVICE-PORT}
          predicates:
            - Path=/api/departments/**
        - id: EMPLOYEE-SERVICE
          uri: http://localhost:${EMPLOYEE-SERVICE-PORT}
          predicates:
            - Path=/api/employees/**