server:
  port: ${GATEWAY_PORT}
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: AUTH-SERVICE
          uri: http://localhost:${AUTH-SERVICE-PORT}
          predicates:
            - Path=/api/auth/**